datamodules:
  # - name: BioMassters
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.PxRegressionStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchBioMasstersDataModule
  #       batch_size: 16
  #       num_workers: 0
  #       root: "/mnt/rg_climate_benchmark/data/geobenchV2/biomassters"
  #       num_time_steps: 6
  #     input_keys: ["image_s1", "image_s2"]
  #     target_key: "mask"
  #     range_vals:
  #       image_s1: [-30, 30]
  #       image_s2: [0, 3000]
  #     target_range_vals: [0, 1000]
  - name: MADOS
    stats_computer:
      _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
      datamodule:
        _target_: geobench_v2.datamodules.GeoBenchMADOSDataModule
        batch_size: 16
        num_workers: 0
        root: "/mnt/rg_climate_benchmark/data/geobenchV2/mados"
      input_keys: ["image"]
      target_key: "mask"
      range_vals:
        image: [0, 0.2]
  # - name: KuroSiwo
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchKuroSiwoDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/geobenchV2/kuro_siwo"
  #     input_keys: ["image_pre_1", "image_pre_2", "image_dem", "image_post"]
  #     target_key: "mask"
  #     range_vals:
  #       image_pre_1: [0, 0.5]
  #       image_pre_2: [0, 0.5]
  #       image_dem: [0, 150]
  #       image_post: [0, 0.5]
  # - name: PASTIS
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchPASTISDataModule
  #       batch_size: 16
  #       num_workers: 0
  #       num_time_steps: 10
  #       root: "/mnt/rg_climate_benchmark/data/geobenchV2/pastis"
  #     input_keys: ["image_s2", "image_s1_asc", "image_s1_desc"]
  #     target_key: "mask"
  #     range_vals:
  #       image_s2: [0, 3000]
  #       image_s1_asc: [0, 1]
  #       image_s1_desc: [0, 1]
  # - name: FLAIR2
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchFLAIR2DataModule
  #       batch_size: 16
  #       num_workers: 0
  #       root: "/mnt/rg_climate_benchmark/data/geobenchV2/flair2"
  #     input_keys: ["image"]
  #     target_key: "mask"
  #     range_vals:
  #       image: [0, 255]
