datamodules:
  # - name: biomassters
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.PxRegressionStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchBioMasstersDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/biomassters"
  #       num_time_steps: 6
  #     input_keys: ["image_s1", "image_s2"]
  #     target_key: "mask"
  #     range_vals:
  #       image_s1: [-1, 1]
  #       image_s2: [0, 1]
  #     clip_min_vals:
  #       image_s1: -1
  #       image_s2: 0
  #     clip_max_vals:
  #       image_s1: 30
  #       image_s2: 3000
  #     target_range_vals: [0, 1000]
    
  # - name: mados
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchMADOSDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       # root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/mados"
  #       root: "/home/nils/projects/GEO-Bench-2/data/mados"
  #     input_keys: ["image"]
  #     target_key: "mask"
  #     range_vals:
  #       image: [0, 0.125]
  #     clip_min_vals:
  #       image: 0
  #     clip_max_vals:
  #       image: 1

  # - name: caffe
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchCaFFeDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/caffe"
  #     input_keys: ["image"]
  #     target_key: "mask"
  #     range_vals:
  #       image: [0, 1]
  #     clip_min_vals:
  #       image: 0
  #     clip_max_vals:
  #       image: 255

  # - name: fotw
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchFieldsOfTheWorldDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/fotw"
  #     input_keys: ["image_a", "image_b"]
  #     target_key: "mask"
  #     range_vals:
  #       image_a: [0, 1]
  #       image_b: [0, 1]
  #     clip_min_vals:
  #       image_a: 0
  #       image_b: 0
  #     clip_max_vals:
  #       image_a: 3000
  #       image_b: 3000

  # - name: spacenet2
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchSpaceNet2DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/spacenet2"
  #     input_keys: ["image_worldview", "image_pan"]
  #     target_key: "mask"
  #     range_vals:
  #       image_worldview: [0, 1]
  #       image_pan: [0, 1]
  #     clip_min_vals:
  #       image_worldview: 0
  #       image_pan: 0
  #     clip_max_vals:
  #       image_worldview: 3000
  #       image_pan: 3000

  # - name: spacenet6
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchSpaceNet6DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/spacenet6"
  #     input_keys: ["image_rgbn", "image_sar"]
  #     target_key: "mask"
  #     range_vals:
  #       image_rgbn: [0, 1000]
  #       image_sar: [0, 100]
  #     clip_min_vals:
  #       image_rgbn: 0
  #       image_sar: 0
  #     clip_max_vals:
  #       image_rgbn: 1000
  #       image_sar: 100

  # - name: spacenet7
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchSpaceNet7DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/spacenet7"
  #     input_keys: ["image"]
  #     target_key: "mask"
  #     range_vals:
  #       image: [0, 1]
  #     clip_min_vals:
  #       image: 0
  #     clip_max_vals:
  #       image: 255

  # - name: spacenet8
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchSpaceNet8DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/spacenet8"
  #     input_keys: ["image_pre", "image_post"]
  #     target_key: "mask"
  #     range_vals:
  #       image_pre: [0, 1]
  #       image_post: [0, 1]
  #     clip_min_vals:
  #       image_pre: 0
  #       image_post: 0
  #     clip_max_vals: 
  #       image_pre: 255
  #       image_post: 255

  # - name: cloudsen12
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchCloudSen12DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/cloudsen12"
  #     input_keys: ["image"]
  #     target_key: "mask"
  #     range_vals:
  #       image: [0, 1]
  #     clip_min_vals:
  #       image: 0
  #     clip_max_vals:
  #       image: 3000

  # - name: everwatch
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.ObjectDetectionStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchEverWatchDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/everwatch"
  #     input_keys: ["image"]
  #     target_key: "label"
  #     range_vals:
  #       image: [0, 1]
  #     clip_min_vals:
  #       image: 0
  #     clip_max_vals:
  #       image: 255

  # - name: dynamic_earthnet
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchDynamicEarthNetDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/dynamic_earthnet"
  #       temporal_setting: "single"
  #     input_keys: ["image_planet","image_s2"]
  #     target_key: "mask"
  #     range_vals:
  #       image_planet: [0, 1]
  #       image_s2: [0, 1]
  #     clip_min_vals:
  #       image_planet: 0
  #       image_s2: 0
  #     clip_max_vals:
  #       image_planet: 3000
  #       image_s2: 3000

  # - name: treesatai
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.ClassificationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchTreeSatAIDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/treesatai"
  #     input_keys: ["image_aerial", "image_s2", "image_s1"]
  #     target_key: "label"
  #     range_vals:
  #       image_aerial: [0, 255]
  #       image_s2: [0, 3000]
  #       image_s1: [0, 1]
  #     clip_min_vals:
  #       image_aerial: 0
  #       image_s1: 0
  #       image_s2: 0
  #     clip_max_vals:
  #       image_aerial: 255
  #       image_s1: 1
  #       image_s2: 3000

  # - name: kuro_siwo
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchKuroSiwoDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/kuro_siwo"
  #     input_keys: ["image_pre_1", "image_pre_2", "image_dem", "image_post"]
  #     target_key: "mask"
  #     range_vals:
  #       image_pre_1: [0, 0.5]
  #       image_pre_2: [0, 0.5]
  #       image_dem: [0, 150]
  #       image_post: [0, 0.5]
  #     clip_min_vals:
  #       image_pre_1: 0
  #       image_pre_2: 0
  #       image_dem: 0
  #       image_post: 0
  #     clip_max_vals:
  #       image_pre_1: 0.5
  #       image_pre_2: 0.5
  #       image_dem: 150
  #       image_post: 0.5


  # - name: pastis
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchPASTISDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       num_time_steps: 10
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/pastis"
  #     input_keys: ["image_s2", "image_s1_asc", "image_s1_desc"]
  #     target_key: "mask"
  #     range_vals:
  #       image_s2: [0, 3000]
  #       image_s1_asc: [0, 1]
  #       image_s1_desc: [0, 1]
  #     clip_min_vals: 
  #       image_s2: 0
  #       image_s1_asc: 0
  #       image_s1_desc: 0
  #     clip_max_vals:
  #       image_s2: 3000
  #       image_s1_asc: 1
  #       image_s1_desc: 1

  # - name: flair2
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchFLAIR2DataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/flair2"
  #       # root: "/home/nils/projects/GEO-Bench-2/data/flair2/"
  #     input_keys: ["image_aerial", "image_elevation"]
  #     target_key: "mask"
  #     range_vals:
  #       image_aerial: [0, 255]
  #       image_elevation: [0, 255]
  #     clip_min_vals:
  #       image_aerial: 0
  #       image_elevation: 0
  #     clip_max_vals:
  #       image_aerial: 255
  #       image_elevation: 255

  # - name: mmflood
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.SegmentationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchMMFloodDataModule
  #       batch_size: 16
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/mmflood"
  #     input_keys: ["image_s1", "image_dem", "image_hydro"]
  #     target_key: "mask"
  #     range_vals:
  #       image_s1: [0, 1]
  #       image_dem: [-1, 1]
  #       image_hydro: [0, 1]
  #     clip_min_vals:
  #       image_s1: 10
  #       image_dem: -1
  #       image_hydro: 0
  #     clip_max_vals:
  #       image_s1: 10
  #       image_dem: 2000
  #       image_hydro: 1

  # - name: benv2
  #   stats_computer:
  #     _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.ClassificationStatistics
  #     datamodule:
  #       _target_: geobench_v2.datamodules.GeoBenchBENV2DataModule
  #       batch_size: 64
  #       num_workers: 4
  #       root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/benv2"
  #     input_keys: ["image_s2", "image_s1"]
  #     target_key: "label"
  #     range_vals:
  #       image_s2: [0, 1]
  #       image_s1: [0, 1]
  #     clip_min_vals:
  #       image_s1: -50
  #       image_s2: 0
  #     clip_max_vals:
  #       image_s1: 100
  #       image_s2: 3000

  - name: m4sar
    stats_computer:
      _target_: geobench_v2.generate_benchmark.utils_dataset_statistics.ObjectDetectionStatistics
      datamodule:
        _target_: geobench_v2.datamodules.GeoBenchM4SARDataModule
        batch_size: 16
        num_workers: 4
        root: "/mnt/rg_climate_benchmark/data/final_geobenchV2/m4sar"
        bbox_orientation: "horizontal"
      input_keys: ["image_optical", "image_sar"]
      target_key: "label"
      range_vals:
        image_optical: [0, 1]
        image_sar: [0, 1]
      clip_min_vals:
        image_optical: 0
        image_sar: 0
      clip_max_vals:
        image_optical: 255
        image_sar: 255